# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e310c38356db790e482dde4df2c739fc27471febcd40052db35cbb5f9fd49e0912ab2c45d9187488df2ab4ec5c1314694b0b617d295a7704611319b94c07fc66

test:
  secret_key_base: 011a61b933310c2af74fe94aae8eb2e7d6c4f5b0a958244d3b16e13039b22bd1f9db5ae27e548efff5b83037a21232dfe2a01fd7760c8f471c3471b2c788c4f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
